### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Instrumentkontroll** [bessmann/instrumentkontroll#16]
Https funkar inte. Fixat det några gånger, men certifikatet gäller visst bara en månad...? Blir alltid nåt fel när jag förnyar det.

**Comment by henriksonnergard** [comment]
Vi löste detta för två veckor sen, eller? Verkar både HTTPS och mail funka nu? @Instrumentkontroll

**Comment by Instrumentkontroll** [comment]
Allt verkar funka

**Comment by henriksonnergard** [comment]
Då stänger vi butiken! 🎉
